CREATE DATABASE `GCD_TEST` /*!40100 DEFAULT CHARACTER SET utf8 */;

CREATE TABLE `GCD_TEST`.`GCD_SOURCE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NUMBER_1` INT NOT NULL,
  `NUMBER_2` INT NOT NULL,
  `ADDED_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_GCD_SOURCE` (`ID` ASC));
  
CREATE TABLE `GCD_TEST`.`GCD_RESULT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `GCD` INT NOT NULL,
  `COMPUTED_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_GCD_RESULT` (`ID` ASC));  